---
- name: check ansible playbook
  hosts: linux
  gather_facts: yes

  tasks:
     - name: check ls home
       shell: "ls -l /home"
       register: command_output
       
     - debug:
         var: command_output.stdout_lines
