---
- name: check ansible playbook
  hosts: linux
  become: true

  tasks:
     - name: This command will change the working directory to somedir/
       ansible.builtin.shell:
        cmd: ls -l /home/gading
